### ISSUE TITLE
Configure SONiC using sonic-py-swsssdk

### ISSUE THREAD

**Issue by lvphuc133** [Azure/sonic-py-swsssdk#43]
Hi All,

I have the following function to add an IP interface to SONiC. After calling this function I can see the newly created entry using redis-cli but look like new configuration hasn't been applied to HW. 
I couldn't find the new interface with "ifconfig", "show interface summary" and ping commands

What else do we need to do here to notify the syncd service to write changes to ASIC?

Thanks,

 def add_ip_inf(self, infName, ipAddr, mask):
        db = swsssdk.ConfigDBConnector()
        db.connect()
        fullAddr = "{}/{}".format(ipAddr, mask)

        # Add IP interface
        try:
            if infName.startswith("Ethernet"):
                resp = db.set_entry("INTERFACE", (infName, fullAddr), {"NULL": "NULL"})
            elif infName.startswith("PortChannel"):
                resp = db.set_entry("PORTCHANNEL_INTERFACE", (infName, fullAddr), {"NULL": "NULL"})
            elif infName.startswith("Vlan"):
                resp = db.set_entry("VLAN_INTERFACE", (infName, fullAddr), {"NULL": "NULL"})
            status = True
        except Exception as e:
            status = False
            resp = str(e)

        return status

**Comment by stcheng** [comment]
@lvphuc133 what are you trying to achieve? are you adding new interfaces or just adding new IPs to existing interfaces?

**Comment by lvphuc133** [comment]
@stcheng For now I need to create new IP interfaces. 

In case of an IP interface exists in the database if I run this snippet will the old IP address will be overwritten or an interface can have multiple addresses?

Thanks,

**Comment by lvphuc133** [comment]
Close this question as new IP interfaces are applied to ASIC in latest SONiC code.
