### ISSUE TITLE
suggest support mset in swss-common

### ISSUE THREAD

**Issue by richard28530** [Azure/sonic-py-swsssdk#50]
lldp-syncd generate LLDP_ENTRY_TABLE and sync to redis one field after one.
this may cause the snmp agent with below syslog from time to time, because snmp agent update may interleaving the hset operations.

i suggest the py-swsssdk support hmset command, and lldp-syncd use this interface to avoid the syslog.

<pre>
Jul 16 18:16:42.268005 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Error updating remote mgmt addr: b'lldp_rem_time_mark'
Jul 16 19:04:20.220476 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark'
Jul 16 21:45:27.373210 dut-testbed-225 WARNING snmp#snmp-subagent message repeated 4 times: [ [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark']
Jul 16 21:45:27.373210 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Error updating remote mgmt addr: b'lldp_rem_time_mark'
Jul 16 21:49:50.834105 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark'
Jul 17 03:55:51.676539 dut-testbed-225 WARNING snmp#snmp-subagent message repeated 11 times: [ [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark']
Jul 17 03:55:51.676835 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Error updating remote mgmt addr: b'lldp_rem_time_mark'
Jul 17 04:19:30.444283 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark'
Jul 17 06:46:16.750943 dut-testbed-225 WARNING snmp#snmp-subagent message repeated 4 times: [ [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark']
Jul 17 06:46:16.751034 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Error updating remote mgmt addr: b'lldp_rem_time_mark'
Jul 17 06:48:38.603073 dut-testbed-225 WARNING snmp#snmp-subagent [sonic_ax_impl] WARNING: Exception when updating lldpRemTable: b'lldp_rem_time_mark'
</pre>

**Comment by anshuv-mfst** [comment]
@lguohan - could you please re-assign the PR, thanks.

**Comment by lguohan** [comment]
we are deprecating sonic-py-swsssdk. all new support should go to sonic-swss-common. 

@qiluo-msft, do we support mset in swss-common?

**Comment by qiluo-msft** [comment]
swss-common re-implement SonicV2Connector, however the `hmset` is not implemented yet.
Please let me know if you have a PR. Otherwise I will add it.
